---
- name: Setting up workload for user
  debug:
    msg: "Setting up workload for user ocp_username = {{ opentlc-mgr }}"

- name: Create Helm Repository for Console
  k8s:
    state: present
    definition: "{{ lookup('file', 'helm_chart_repository.yaml' ) | from_yaml }}"

- name: Deploy ArgoCD Namespace Operator
  when: install_near_rt_ric_deploy_argocd_namespace_operator | bool
  include_role:
    name: install_operator
  vars:
    install_operator_action: install
    install_operator_name: argocd-namespace-operator
    install_operator_namespace: openshift-operators
    install_operator_channel: >-
      {{ install_near_rt_ric_deploy_argocd_namespace_operator_channel }}
    install_operator_automatic_install_plan_approval: >-
      {{ install_near_rt_ric_deploy_argocd_namespace_operator_automatic_install_plan_approval | default(true) }}
    install_operator_starting_csv: >-
      {{ install_near_rt_ric_deploy_argocd_namespace_operator_starting_csv }}
    install_operator_catalogsource_setup: true
    install_operator_catalogsource_name: argocd-namespace-operator-catalogsource
    install_operator_catalogsource_namespace: openshift-operators
    install_operator_catalogsource_image: >-
      {{install_near_rt_ric_deploy_argocd_namespace_operator_catalog_image }}
    install_operator_catalogsource_image_tag: >-
      {{ install_near_rt_ric_deploy_argocd_namespace_operator_catalog_image_tag }}

# Leave this as the last task in the playbook.
# --------------------------------------------
- name: workload tasks complete
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent | bool
